mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    - MYSQL_USER=petclinic
    - MYSQL_PASSWORD=petclinic
    - MYSQL_DATABASE=petclinic
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"
jenkins:
  image: abhi/jenkins-1
  ports:
    - "8081:8080"
nexus:
  image: sonatype/nexus3
  ports:
    - "8082:8081"
sonar:
  image: sonarqube
  ports:
    - "9000:9000"
